
[tool.pyright]
typeCheckingMode = "basic"  # or "strict" for stricter checking
pythonVersion = "3.12"      # specify your Python version
exclude = ["**/node_modules", "**/__pycache__"]
reportMissingImports = true
reportMissingTypeStubs = false

[tool.ruff]
# Same as Black
line-length = 88
indent-width = 4

# Enable specific rules
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
]

# Ignore specific rules
ignore = [
    "E501"  # Line too long (handled by formatter)
]

# Exclude files/directories
exclude = [
    ".git",
    ".venv",
    "__pycache__",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending-style = "minimal"
